name: cordis
description: "Chord Map Application."
publish_to: 'none'

version: 1.0.0+11

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  carousel_slider_plus: ^7.1.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.2
  flutter_speed_dial: ^7.0.0
  path_provider: ^2.1.1
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  firebase_analytics: ^12.0.2
  google_sign_in: ^6.2.1
  cloud_functions: ^6.0.3
  file_picker: ^8.1.4
  syncfusion_flutter_pdf: ^31.2.18
  flutter_launcher_icons: ^0.14.4
  collection: ^1.19.1
  numberpicker: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  fl_chart: ^0.69.0                # Charts for data visualization (PDF analysis preview)

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/app_icon_512.png"
  adaptive_icon_foreground: "assets/logos/app_icon_512.png"
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/graphics/

  fonts:
    - family: Asimovian
      fonts:
        - asset: assets/fonts/Asimovian-Regular.ttf
          weight: 400

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth_wght.ttf
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth_wght.ttf
          style: italic

    - family: Atkinson
      fonts:
        - asset: assets/fonts/AtkinsonHyperlegible-Regular.ttf
        - asset: assets/fonts/AtkinsonHyperlegible-Bold.ttf
          weight: 700
        - asset: assets/fonts/AtkinsonHyperlegible-Italic.ttf
          style: italic
        - asset: assets/fonts/AtkinsonHyperlegible-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf

    - family: FormaDJRMicro
      fonts:
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-Regular-Testing.otf
          weight: 400
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-Italic-Testing.otf
          weight: 400
          style: italic
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-Medium-Testing.otf
          weight: 500
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-MediumItalic-Testing.otf
          weight: 500
          style: italic
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-Bold-Testing.otf
          weight: 700
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-BoldItalic-Testing.otf
          weight: 700
          style: italic
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-ExtraBold-Testing.otf
          weight: 800
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-ExtraBoldItalic-Testing.otf
          weight: 800
          style: italic
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-Black-Testing.otf
          weight: 900
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-BlackItalic-Testing.otf
          weight: 900
          style: italic
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-Light-Testing.otf
          weight: 300
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-LightItalic-Testing.otf
          weight: 300
          style: italic
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-ExtraLight-Testing.otf
          weight: 200
        - asset: assets/fonts/formaDJRMicro/FormaDJRMicro-ExtraLightItalic-Testing.otf
          weight: 200
          style: italic









